name: 'Exercise test checks'

on: 
  push:
    branches:
      - master

jobs:
  init:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      # Setup Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv
      
      - name: Install dependencies
        run: |
          pwd && ls
          pipenv install -r ./requirements.txt -d

      - id: cache-pipenv
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          path: |
            ./Pipfile
            ./Pipfile.lock

  lint:
    needs: init
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Lint checks
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip

      - name: Restore cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          path: |
            ./Pipfile
            ./Pipfile.lock

      - run: pylint account.py

  # test:
  #   needs: lint
  #   runs-on: "ubuntu-latest"
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Test script
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.10'
  #         cache: pip

  #     - name: Restore cache
  #       uses: actions/cache@v3
  #       with:
  #         key: cache-dependencies-${{ github.sha }}
  #         path: ./*

  #     - run: pytest test_account.py