name: 'Exercise test checks'

on: 
  push:
    branches:
      - master

jobs:
  init:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Init dependencies
        working-directory: ./account_oop_exercise
        run: |
          pip install --upgrade pip
          pip install pylint pytest

      - name: Upload cache
        uses: actions/cache@v3
        with:
          key: cache-dependencies-${{ github.run_id }}
          path: ~/.cache/pip



  lint:
    needs: init
    runs-on: "ubuntu-latest"
    steps:
      - name: Restore cache
        uses: actions/cache@v3
        with:
          key: cache-dependencies-${{ github.run_id }}
          path: ~/.cache/pip

      - name: Lint checks
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
      - run: pylint account_oop_exercise/test_account.py

  test:
    needs: lint
    runs-on: "ubuntu-latest"
    steps:
      - name: Restore cache
        uses: actions/cache@v3
        with:
          key: cache-dependencies-${{ github.run_id }}
          path: ~/.cache/pip

      - name: Test script
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
      - run: pytest test_account.py