name: 'Exercise test checks'

on: 
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  runs-on: "ubuntu-latest"
  steps:
    - name: Checkout
      uses: action/checkout@v4
    
    - name: Init dependencies
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: 'account_oop_exercise/requirements.txt'
      run: pip install -r account_oop_exercise/requirements.txt

    - name: Lint checks
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache-dependency-path: 'account_oop_exercise/requirements.txt'
      run: pylint account_oop_exercise/test_account.py

    - name: Test script
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache-dependency-path: 'account_oop_exercise/requirements.txt'
      run: pytest account_oop_exercise/test_account.py