name: 'Exercise test checks'

on: 
  push:
    branches:
      - master

jobs:
  init:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      # Setup Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv

      - id: cache-pipenv
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.locl') }}
          path: ~/.local/share/vurtualenvs
      
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pwd && ls
          pipenv install -r ./requirements.txt --deploy


        # cache-dependency-path: |
        #   ./account_oop_exercise/Pipfile.lock
        #   ./account_oop_exercise/Pipfile

        # working-directory: ./account_oop_exercise

  # lint:
  #   needs: init
  #   runs-on: "ubuntu-latest"
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Lint checks
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.10'
  #         cache: pip

  #     - name: Restore cache
  #       uses: actions/cache@v3
  #       with:
  #         key: cache-dependencies-${{ github.sha }}
  #         path: ./*

  #     - run: pylint account_oop_exercise/test_account.py

  # test:
  #   needs: lint
  #   runs-on: "ubuntu-latest"
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Test script
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.10'
  #         cache: pip

  #     - name: Restore cache
  #       uses: actions/cache@v3
  #       with:
  #         key: cache-dependencies-${{ github.sha }}
  #         path: ./*

  #     - run: pytest test_account.py