name: 'Exercise test checks'

on: 
  push:
    branches:
      - master

jobs:
  init:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: ./account_oop_exercise
    steps:
      - uses: action/checkout@v4
      - name: Init dependencies
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
          cache-dependency-path: 'requirements.txt'
      - run: pip install -r requirements.txt

  # lint:
  #   runs-on: "ubuntu-latest"
  #   defaults:
  #     run:
  #       working-directory: ./account_oop_exercise
  #   steps:
  #     - name: Lint checks
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.10'
  #         cache-dependency-path: 'requirements.txt'
  #       run: pylint test_account.py

  # test:
  #   runs-on: "ubuntu-latest"
  #   defaults:
  #     run:
  #       working-directory: ./account_oop_exercise
  #   steps:
  #     - name: Test script
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.10'
  #         cache-dependency-path: 'requirements.txt'
  #       run: pytest test_account.py