name: 'Exercise test checks'

on: 
  push:
    branches:
      - master

jobs:
  init:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pipenv'
          cache-dependency-path: |
            ./account_oop_exercise/Pipfile.lock
            ./account_oop_exercise/Pipfile
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - run: pipenv install

      - name: Upload cache
        uses: actions/cache@v3
        with:
          key: cache-dependencies-${{ github.sha }}
          path: ./*


        # working-directory: ./account_oop_exercise

  # lint:
  #   needs: init
  #   runs-on: "ubuntu-latest"
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Lint checks
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.10'
  #         cache: pip

  #     - name: Restore cache
  #       uses: actions/cache@v3
  #       with:
  #         key: cache-dependencies-${{ github.sha }}
  #         path: ./*

  #     - run: pylint account_oop_exercise/test_account.py

  # test:
  #   needs: lint
  #   runs-on: "ubuntu-latest"
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Test script
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.10'
  #         cache: pip

  #     - name: Restore cache
  #       uses: actions/cache@v3
  #       with:
  #         key: cache-dependencies-${{ github.sha }}
  #         path: ./*

  #     - run: pytest test_account.py