name: 'Exercise test checks'

on: 
  push:
    branches:
      - master
    paths:
      - account_oop_exercise

jobs:
  init:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Init dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
          cache-dependency-path: 'account_oop_exercise/'
      - run: |
          pip install --upgrade pip
          pip install pylint pytest 

  lint:
    needs: init
    runs-on: "ubuntu-latest"
    steps:
      - name: Lint checks
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
          cache-dependency-path: 'account_oop_exercise/'
      - run: pylint account_oop_exercise/test_account.py

  test:
    needs: lint
    runs-on: "ubuntu-latest"
    steps:
      - name: Test script
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
          cache-dependency-path: 'account_oop_exercise/'
      - run: pytest account_oop_exercise/test_account.py