name: 'Exercise test checks'

on: 
  push:
    branches:
      - master

jobs:
  init:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      # Setup Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
      
      - name: Upgrade pip
        run: |
          pip install --upgrade pip

  lint:
    needs: init
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Lint checks
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip

      - name: Install Linter
        run: |
          pip install pylint

      - run: pylint account.py

  test:
    needs: lint
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Test script
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip

      - name: Install Pytest
        run: |
          pip install pytest

      - run: pytest test_account.py